### ISSUE TITLE
Supported Devices

### ISSUE THREAD

**Issue by Amar-Chaudhari** [datacenter/nxos#1]
Hello

Could you please write about which devices/OS version will support this ?
I think previously it was supported only by N9k.

Regards,

**Comment by abhinavmodi** [comment]
Hi Amar

Most samples currently listed here are supported on Nexus 5k, 6k and 7k. NX-API was introduced on these platforms since Release 7.2 (June 2015)

**Comment by Amar-Chaudhari** [comment]
Hi Abhinav,

Great, Thank you for the information !
